name: my_portifolio
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^0.1.2
  mdi: ^1.0.1
  google_maps_flutter: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^5.4.2
  cloud_firestore: ^0.13.4+1

flutter:


  uses-material-design: true

  assets:
   - assets/images/image.jpg